# Generated by Django 4.2.14 on 2024-09-11 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(unique=True)),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('match_date', models.DateTimeField(verbose_name='Date Of Match')),
                ('home_possession', models.FloatField()),
                ('away_possession', models.FloatField()),
                ('home_total_shots', models.IntegerField()),
                ('away_total_shots', models.IntegerField()),
                ('home_on_target', models.IntegerField()),
                ('away_on_target', models.IntegerField()),
                ('home_off_target', models.IntegerField()),
                ('away_off_target', models.IntegerField()),
                ('home_blocked', models.IntegerField()),
                ('away_blocked', models.IntegerField()),
                ('home_passing_percent', models.FloatField()),
                ('away_passing_percent', models.FloatField()),
                ('home_clear_cut_chances', models.IntegerField()),
                ('away_clear_cut_chances', models.IntegerField()),
                ('home_corners', models.IntegerField()),
                ('away_corners', models.IntegerField()),
                ('home_offsides', models.IntegerField()),
                ('away_offsides', models.IntegerField()),
                ('home_tackles', models.FloatField()),
                ('away_tackles', models.FloatField()),
                ('home_aerial_duels', models.FloatField()),
                ('away_aerial_duels', models.FloatField()),
                ('home_saves', models.IntegerField()),
                ('away_saves', models.IntegerField()),
                ('home_fouls_committed', models.IntegerField()),
                ('away_fouls_committed', models.IntegerField()),
                ('home_fouls_won', models.IntegerField()),
                ('away_fouls_won', models.IntegerField()),
                ('home_yellow_cards', models.IntegerField()),
                ('away_yellow_cards', models.IntegerField()),
                ('home_red_cards', models.IntegerField()),
                ('away_red_cards', models.IntegerField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team_set', to='altprem.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team_set', to='altprem.team')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='altprem.season')),
            ],
        ),
    ]
